FROM registry.access.redhat.com/ubi8/ubi

RUN mkdir -p /2048-directory \
 && dnf install -y wget gcc \
 && dnf clean all 

WORKDIR /2048-directory

COPY 2048.c /2048-directory/

RUN gcc -o 2048 2048.c

CMD /2048-directory/2048
